version: '3'

networks:
  net:
    driver: bridge

services:

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_USER: "leandro"
      POSTGRES_DB: "poupaOnline"
    networks:
      - net

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - net

  app:
    container_name: app
    build: 
      context: ./app
      dockerfile: Dockerfile
    networks:
      - net

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - net